#include <fc_api.h>
#include "page.h"
#include "screen.h"
#include "version.h"
#include "history.h"
#include "gemini.h"

const char about_text[] =
  "# About " VERSION "\n"
  "\n"
  "=> //virgil.jedimatt42.com/ti994a/virgil/ Virgil99 homepage\n"
  "\n"
  "## Mouse usage:\n"
  "\n"
  "Scroll by clicking the mouse in the right hand 10 character column of the\n"
  "screen. The mouse cursor will change when you hover over the region to\n"
  "indicate the paging or scrolling action that will occur. Note, the action\n"
  "occurs on mouse-up. You cannot hold the button down at this time. Near the\n"
  "top right, is page up. Near the bottom right is page down. Closer to the\n"
  "middle right is line up and line down.\n"
  "\n"
  "The top row the of the screen contains the title, and memory usage on the left.\n"
  "On the right are 'buttons' you can click to operate or interrupt the browser.\n"
  "\n"
  "* ADDRESS - opens a text input dialog with the current URL to edit\n"
  "* BACK - reload the previous page\n"
  "* STOP - stop loading the current page. This will take the place of the BACK button while a page is loading\n"
  "* QUIT - exit the browser\n"
  "\n"
  "## Keyboard usage:\n"
  "* ESC(F9) - exit the browser\n"
  "* FCTN X - scroll down\n"
  "* FCTN E - scroll up\n"
  "* FCTN S - load previous page\n"
  "* CTRL X - page down\n"
  "* CTRL E - page up\n"
  "* CTRL S - stop loading page\n"
  "* CTRL A - open address\n"
  "\n"
  "## Supported URL formats:\n"
  "\n"
  "No external protocols are supported at this time.\n"
  "gemini://<hostname>/path\n"
  "//<hostname>/path\n"
  "about:\n"
  "\n"
  "## Link Colors:\n"
  "\n"
  "=> gemini://deadend.net Gemini URLs are Green\n"
  "=> gopher://deadend.net Gopher URLS are Yellow\n"
  "=> http://deadend.net HTTP URLS are Pale Yellow\n";

